POST http://localhost:4004/admin/addProductCategory
Content-Type: application/json

{
    "payload": [{
    "ID": 11,
    "Name": "test order 1",
    "Description": "this is a test entry"
    }]
}

###

POST http://localhost:4004/admin/addCategoryClass
Content-Type: application/json

{
    "payload": [{
    "ID": 11,
    "Name": "test order 1",
    "Description": "this is a test entry"
    }]
}

###

POST http://localhost:4004/admin/multipleLoggingInstances
Content-Type: application/json

{
    "payload": [{
    "ID": 11,
    "Name": "test order 1",
    "Description": "this is a test entry"
    }]
}

###

POST http://localhost:4004/admin/onlyOneInstance
Content-Type: application/json

{
    "payload": [{
    "ID": 11,
    "Name": "test order 1",
    "Description": "this is a test entry"
    }]
}

####
GET http://localhost:4004/orders/selectProductCategory(id=4)
Content-Type: application/json